---
title: "Updating the Target Platform used by 4diac IDE"
url: doc/development/ideUpdateTargetPlatform.html
---

= Updating the Target Platform used by 4diac IDE
:lang: en

For upgrading to new Eclipse platform versions the following steps need to be done:

* Update org.eclipse.fordiac.ide.product.target in the org.eclipse.fordiac.ide.product plug-in
** Locate https://github.com/eclipse-4diac/4diac-ide/blob/develop/plugins/org.eclipse.fordiac.ide.product/org.eclipse.fordiac.ide.product.target
** Open it in a plain text editor
** Go through all entries check for new urls and new versions
** At the end open the `org.eclipse.fordiac.ide.product.target` in the target editor to verify all upgrades work. Resolve any problems accordingly
* Update pom.xml in the 4diac IDE's source root directory. 
  At least the following steps have to be done:
** Check tycho.version
** Update tycho-repo.url to the new target platform version
** Check org.eclipse.equinox.executable version range. 
  Attention this has to be done on two places in the file. +
For the version check the latest https://download.eclipse.org/eclipse/downloads/[release overview page]. 
There check for _Eclipse Platform Launcher Executables_.
* Regenerate all model and model edit code from the models plug-in.
* Run product from Eclipse IDE using product editor, i.e., press the synchronize button and then the "Launch an Eclipse Application"
* Run Maven install for pom.xml in the 4diac IDE's source root directory locally
* Test if the generated product can be executed. The generated products are in: +
`/org.eclipse.4diac.ide/plugins/org.eclipse.fordiac.ide.product/target/products/org.eclipse.fordiac.ide.product
* Push to Gerrit so that CI build can also check if it is working
