= [[topOfPage]]Building 4diac FORTE Docker Images
:lang: en


== Creating the Image

Two Docker files are provided in the `./docker/` folder of the 4diac FORTE repository. 
The first one is a docker image that runs 4diac FORTE in it. 
The second one is a docker image that is used to build 4diac FORTE for many architectures and devices. 
Currently it builds for:

* linux32
* raspberry pi (and BeagleBone Black). 
  Not valid for the raspberry pi zero
* embrick
* (COMMING SOON) RevPi
* (COMMING SOON) WAGO

In both docker images 4diac FORTE is built with the following modules:

* UTILS
* CONVERT
* IEC61131
* Arrowhead
* HTTP (port 8080)
* LUA
* MQTT
* OPC UA (with security)

and the devices with their corresponding IO module.

The docker image of 4diac FORTE has the binary located in `/usr/forte_output/linux32/forte`.

The builder docker image has the binaries located in `/usr/forte_output/`.

To build the docker images, you need to go to the root folder of the 4diac FORTE repository and execute (don't forget the point at the end):

----
docker build -t forte -f docker/Dockerfile_forte .
----

and

-----
docker build -t forte_builder -f docker/Dockerfile_builder .
-----

== Start Containers

To start a 4diac FORTE instance, just execute:

----
docker run -d -p 61499:61499 -p 4840:4840 forte:latest
----

the `-d` option starts the container in the background. 
The `-p` options maps the outside port to the inside.

To start 4diac FORTE with other listening port, execute:

----
docker run -d -p 61500:61500 -p 4840:4840 forte:latest
/usr/forte_output/linux32/forte -c localhost:61500
----

The most common way of start the forte_builder image is as follow:
----
docker run -it forte_builder:latest
----

You'll then be inside the container and can browse it.

To copy the 4diac FORTE binaries to the local folder, execute:
----
docker create --name temp_container forte_builder:latest && docker cp temp_container:/usr/forte_output/ ./ && docker rm temp_container
----

== [[whereToGoFromHere]]Where to go from here?

Now that you installed the required tools, it's time to start using
them. Take a look at the following page:

link:../tutorials/overview.html[Step by step tutorial]

If you want to build a 4diac FORTE, here is a quick link back:

link:./install.html[Install Eclipse 4diac]

If you want to go back to the Start Here page, we leave you here a fast
access

xref:../index.adoc[Start Here page]

Or link:#topOfPage[Go to top]
