= [[topOfPage]]Using Eclipse 4diac with a Lego Mindstorm EV3
:lang: en


This page is for compiling 4diac FORTE for the Lego Mindstorm EV3. 
For information about the parameters to be used, go to the link:../io_config/EV3.adoc[EV3 IO configuration] page.

== [[ev3_introduction]]About the Lego Mindstorm EV3 and ev3dev

Lego Mindstorm is a series of kits from Lego, whose flexibility allows constructing different systems which can be controlled and sensed by the user, using the inputs and outputs. 
This document focuses on how to implement 4diac FORTE on the specific model Lego Mindstorm EV3(LMSEV3).
To know more about the LMSEV3 you can visit its Wikipedia https://en.wikipedia.org/wiki/Lego_Mindstorms_EV3[page].

The LMSEV3 comes with its own software, but work has been done to implement a Linux distribution that can run on it. 
ev3dev is a Debian Linux-based operating system that can run on the LMSEV3. 
More information about capabilities of ev3dev can be found on its http://www.ev3dev.org/[website]. 
The procedure to make ev3dev run in a LMSEV3 is similar to running a Linux operating system on a Raspberry Pi.
The best and fastest way to implement ev3dev in a LMSEV3 is following the instruction on its http://www.ev3dev.org/docs/getting-started/[getting started page].
Basically, what must be done is to download the ev3dev image and write it on a mini SD card (yes, without an mini SD card you won't be able to run it), insert it in the LMSEV3 and boot it.

So, what will you find in this special Linux version for LMSEV3? 
First, you'll find a menu in the screen of the LMSEV3 that can be accessed using the buttons. 
And secondly, you will be able to connect using SSH the same way you would do it on a Raspberry Pi, the BeagleBone Black or any other Linux-based operating system and go through the folder system of the ev3dev that is prepared for the LMSEV3. 
To access all the I/O of the LMSEV3 (including the buttons, LED and the screen), there are specific explanations in http://www.ev3dev.org/docs/tutorials/[ev3dev tutorials page], but 4diac FORTE takes care of accessing them and you as user will only work with normal I/O Function Blocks as IX, QX, IW, QW and so on.

To access the LMSEV3 via SSH you'll have to setup a network connection first. 
The easiest way is using a WiFi dongle that can be connected to the LMSEV3's USB port. 
A few compatible WiFi dongles are listed https://www.ev3dev.org/docs/networking/[here]. 
Once you have a WiFi dongle, you can connect to a WiFi network via "Wireless and Networks" on the start menu. 
Power on WiFi, scan for available networks and then connect to it. 
If you successfully connected to a WiFi network, the IP address of the LMSEV3 will be shown in the top left corner of the
screen. To make life easier, setup your router to use static IP addresses. 
Now you can setup an SSH connection on your computer. 
How to setup a connection with PuTTY or WinSCP is explained https://www.ev3dev.org/docs/tutorials/connecting-to-ev3dev-with-ssh/[here]

With the LMSEV3 running the ev3dev and it being accessible through SSH, the next thing to do is to install and run 4diac FORTE in it. 
Similar to other platforms, you have two possibilities. 
The first one is to transfer the source code to the ev3dev (using https://winscp.net/eng/download.php[WinSCP] in Windows or the "scp" command in Linux), installing the compiler and other necessary tools (C++ compiler and CMake, mainly) and compiling it directly in the LMSEV3. 
The second option is to use a cross-compiler. 
This means that you will code and compile in your desktop machine, and then send the executable to the LMSEV3 and run it there. The first option is easier to implement but is slower to compile. 
The second one is much faster but you will have to setup of the environment on your desktop machine. 
With Docker, it's much easier to do the second option. 
The first option should be used only when installing Docker is not possible. 
Especially if you will be compiling several times, you should try the second option. 
Getting your desktop machine to cross-compile for the ev3dev is not easy, but a complete step by step guide is presented https://www.ev3dev.org/docs/tutorials/using-docker-to-cross-compile/[here].

To set up the cross-compiler, the following steps must be done:

NOTE: All commands starting with `docker` are run in the command prompt of your host computer, all other commands are run inside of your docker container (if you cross-compile) or inside of your EV3!

. Install https://www.docker.com/[Docker]. 
  A detailed installation guide can be found https://docs.docker.com/engine/install/[here]. 
  Docker will be used to run the ev3dev image on your computer. 
  This allows you to build a EV3 specific 4diac FORTE with the power of your computer.
. Follow the steps https://www.ev3dev.org/docs/tutorials/using-docker-to-cross-compile/[here] to download the ev3dev cross-compiler image.
. After setting up the image, run a Docker container with the following command:
+
----
docker run --rm -it -v $(pwd):/src -w /src ev3cc
----
+
Let's break it down:

* `run` runs a new container
* `--rm` this will make sure, that the container is thrown away once you are done.
* `-it` this will make the command prompt available inside of your container.
* `-v <host-path>:<container-path>` this will make a directory of your host computer accessible from within the container. 
  Make sure to specify the host path according to your OS. 
  On Windows hosts, you might experience some problems with file paths, e.g. when using git bash on Windows you need to use double backslash as file separator.
* `-w <container-path>` this will specify the working directory within your container.
* ` ev3cc` this is the name of your Docker image.
. Now, that the container is running, you need to install the necessary tools that you need to compile a 4diac FORTE in your container. 
  Run the following commands:
+
----
sudo apt-get update sudo apt-get install build-essential sudo apt-get
install cmake
----
+
To save time the next time, you can create a new Docker image from your current container. 
This will save all the changes and you won't have to do it again. Use the following command:
+
----
docker commit [CONTAINER_ID] [new_image_name]
----
+
To see all your currently running containers (and their ID), use:
+
----
docker ps -a
----
+
and to see whether it worked and you saved a new image use:
+
----
docker images
----
. If you haven't done so yet, transfer a 4diac FORTE folder to the folder that you are sharing with your container, or transfer it directly
to your EV3 with WinSCP if you are compiling there.
. Next, navigate to the transferred 4diac FORTE folder (in the command prompt within your container) and execute:
+
----
. setup_lmsEv3.sh
----
+
which is going to setup everything in the bin/ev3dev folder. 
Next, you should go into the bin/ev3dev folder and simply execute "make" to start the compilation.
. Now you have compiled a 4diac FORTE that can run inside of your brick!
  If you already set up the network connection to your brick, you can send `forte` to your brick using WinSCP. 
  Check, whether execution rights are enabled for `forte`.

If you want to compile directly in your EV3, then start at step 4 and perform everything with the command prompt of your EV3 (to get the command prompt inside of your EV3, connect to it with PuTTY).

Remember, when you create your own FBs, you should add these to the 4diac FORTE folder, adjust the CMakefiles.txt and compile again. 
In the link:./index.adoc#ownFORTE[example] section, it is explained how to do this.

== Troubleshooting

If you have limited rights on your host computer (e.g. your company manages certain settings) and therefore can't use Docker, you can install a Linux distribution in a virtual machine and run your Docker container there. 
If you are having trouble setting up a virtual machine on your windows machine, try to disable "Hyper-V". 
You can follow the instructions https://docs.microsoft.com/en-us/troubleshoot/windows-client/application-management/virtualization-apps-not-work-with-hyper-v[here].

If you are having problems connecting to your EV3, try whether the network connection is working and ping your EV3. 
If your EV3 is connected, the IP address should be shown an the top of the screen.
----
ping [IP ADRESS]
----

If you are having problems including external modules, add this to your `setup_lmsEv3.sh file` and run it again.

----
-DFORTE_EXTERNAL_MODULES_DIRECTORY=”/src/forte/ext_mod”
-DFORTE_MODULE_EV3=ON
----

You must have a folder `ext_mod` within your `forte` folder. Your modules are then added as subfolders to `ext_mod`. 
In this case, a module called "EV3" is added.


== [[whereToGoFromHere]]Where to go from here?

If you want to build a 4diac FORTE, here is a quick link back:

xref:./index.adoc[Install Eclipse 4diac]

After you installed all required tools, it's time to start using them. 
Take a look at the tutorials - a step by step guide:

xref:../tutorials/overview.adoc[Step 0 - 4diac IDE Overview]

If you want to go back to the Start Here page, we leave you here a fast
access

xref:../index.adoc[Where to Start]

Or link:#topOfPage[Go to top]
