---
# This header is for providing additional information to hugo for the website generation it ignored by asciidoctor
title: "Installation"
url: doc/installation/overview.html
page_css_file: /4diac/css/4diac_doc.css
layout: "doc-overview"
sidebar: 
  - sb-doc
---

= Installation
:lang: en
:imagesdir: img

== [[IDE]]4diac IDE

You can download the latest version of 4diac IDE for your operating system from our https://eclipse.dev/4diac/download/[downloads] page.
Simply unzip it to a folder of your choosing and launch the contained executable to start working with 4diac IDE.
It already comes with a rich set of _Standard Libraries_ for developing applications.

=== [[ownIDE]]Building your own 4diac IDE

If you want to try out the latest features, you can also build your own 4diac IDE from the sources in the https://github.com/eclipse-4diac/4diac-ide[Git] repository.
For more information, please have a look at the xref:../development/building4diac.adoc#buildFromSource[installation steps] on how to build your own 4diac IDE.

== [[FORTE]]4diac FORTE

We provide pre-built versions of 4diac FORTE for various common operating systems and targets on our https://eclipse.dev/4diac/download/[downloads] page.
This will allow you to quickly get started with deploying and running applications on 4diac FORTE.

If you want to start using 4diac IDE right away, you can skip the rest of the page and go directly to the xref:../tutorials/overview.adoc[step by step tutorial] or the xref:../doc_overview.adoc[Start Here-page].

=== [[ownFORTE]]Building your own 4diac FORTE

If there is no pre-built version that suits your needs or you just want to try out the latest features, you can also build 4diac FORTE from the sources in the https://github.com/eclipse-4diac/4diac-forte[Git] repository.

The following steps will walk you through how to build 4diac FORTE on your own computer.
If you want to build 4diac FORTE for an embedded target, please have a look at the link:#forteOtherPlatforms[links] on the bottom of this page.

==== [[FORTEPrerequisites]]Prerequisites

For building 4diac FORTE, you need to install some dependencies based on your operating system.

[tabs,sync-group-id=os]
====
Linux::
+
--
The following steps describe how to install the required dependencies for building 4diac FORTE on Linux.

[tabs]
======
Ubuntu::
+
If you are on Ubuntu Noble (24.04), Jammy (22.04), or Focal (20.04), you need to first add the official CMake repository to get the latest CMake version:
+
[source,bash]
----
apt-get install wget
wget https://apt.kitware.com/kitware-archive.sh
. kitware-archive.sh
----
+
You can use the following command(s) to install the required dependencies:
+
[source,bash]
----
apt-get install cmake g++ gcc git ninja-build
----

Arch::
+
You can use the following command(s) to install the required dependencies:
+
[source,bash]
----
pacman -S cmake gcc git ninja
----
======
--

Windows::
+
--
The following steps describe how to install the required dependencies for building 4diac FORTE on Windows.

You can download Git for Windows https://git-scm.com/downloads/win[here] and CMake https://cmake.org/download/[here].
Follow the steps in the installation wizard and be sure to select adding Git and CMake to the PATH variable in the respective step.
To avoid any problems, you should choose an installation path that does not contain spaces.

Please follow the instructions below for setting up the compiler of your choice:

* xref:./mingw.adoc[Setting up MinGW-w64 (recommended)]
* xref:./visualstudio.adoc[Setting up Microsoft Visual Studio]

The remaining instructions are focused on MinGW-w64, which is therefore particularly recommended for less experienced users.
--
====

link:#FORTE[back]

==== [[FORTEClone]]Clone the Git repository

You can use the following command to clone the Git repository of 4diac FORTE:

[script,bash]
----
git clone https://github.com/eclipse-4diac/4diac-forte.git
----

This will create a new folder `4diac-forte` in the current working directory.

link:#FORTE[back]

==== [[FORTEBuild]]Build 4diac FORTE

You can use the following commands to build and install 4diac FORTE in a local subfolder:

[tabs,sync-group-id=os]
====
Linux::
+
[source,bash]
----
cd 4diac-forte
cmake -G Ninja --preset posix-shared-debug
cmake --build build/posix-shared-debug
cmake --install build/posix-shared-debug
----
+
The last command will install 4diac FORTE into `install/posix-shared-debug`.

Windows::
+
[source,bash]
----
cd 4diac-forte
cmake -G Ninja --preset windows-shared-debug
cmake --build build/windows-shared-debug
cmake --install build/windows-shared-debug
----
+
The last command will install 4diac FORTE into `install/windows-shared-debug`.
====

link:#FORTE[back]

=== [[ownModule]]Building your own modules

The following steps will walk you through how to build your own modules for 4diac FORTE.

First, you will need to set up a build environment according to the link:#FORTEPrerequisites[instructions] above.
You will then need to export your module from 4diac IDE.
The export is described in xref:../tutorials/createowntypes.adoc#exportTypes[step 4] of the tutorial.
When exporting the module, please make sure you check the _Export CMakeLists.txt_ option.

You can then use the following commands to build and install your module in a local subfolder:

[source,bash]
----
cd path/to/module
cmake -G Ninja -B build -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX:PATH=path/to/forte
cmake --build build
cmake --install build
----

If you downloaded a pre-built version of 4diac FORTE, `path/to/forte` should point to the contents of the extracted archive.
If you built your own version of 4diac FORTE, it should point to the sub-folder inside `install`, for example, `4diac-forte/install/*-shared-debug`.

link:#FORTE[back]

=== [[forteOtherPlatforms]]Building 4diac FORTE for other platforms

* xref:./raspi.adoc[Setting up 4diac FORTE for RaspberryPi]
* xref:./wago.adoc[Setting up 4diac FORTE for Wago PFCs PLC]
* xref:./legomindstormev3.adoc[Setting up 4diac FORTE for Lego Mindstorms EV3]
* xref:./freertos_lwip.adoc[Setting up 4diac FORTE for freeRTOS + LwIP]

== [[whereToGoFromHere]]Where to go from here?

Now that you installed the required tools, it's time to start using them. Take a look at the tutorials

* xref:../tutorials/overview.adoc[A step by step guide]
* xref:./bootwithforte.adoc[Start 4diac FORTE after boot on Linux based systems]

If you want to go back to the Where to Start page, we leave you here a fast access:

xref:../doc_overview.adoc[Where to Start]

Or link:#top[Go to top]
