---
title: "openPOWERLINK"
url: doc/communication/openpowerlink.html
---

= openPOWERLINK

https://sourceforge.net/projects/openpowerlink/[openPOWERLINK] is an Open Source Industrial Ethernet stack implementing the https://en.wikipedia.org/wiki/Ethernet_Powerlink[Ethernet POWERLINK] protocol.

== Prerequisites

The following is needed in order to use openPOWERLINK with 4diac FORTE:

* http://sourceforge.net/projects/openpowerlink/[openPOWERLINK V1.8.0]
* http://sourceforge.net/projects/tinyxml/[TinyXML]

== Instructions

The openPOWERLINK V1.8.0 stack from SourceForge should be compiled using at least the following options in CMake:

* `CFG_POWERLINK_CHM`
* `CFG_POWERLINK_PROCESS_IMAGE`
* `CFG_X86_WINDOWS_DLL` (only available on Windows)

If compiled on Windows the resulting DLL and LIB must be copied to the main openPOWERLINK-V1.8.0 folder.

TinyXML can also be downloaded from SourceForge. 
4diac FORTE CMake has to be configured as follows:

* check `FORTE_MODULE_POWERLINK`
* set `FORTE_MODULE_POWERLINK_LIB_DIR` to [OPENPOWERLINK-V1.08.0_HOME]
* set `FORTE_MODULE_POWERLINK_TINYXML_DIR` to the directory where you unpacked TinyXML

For communication through opwenPOWERLINK, instantiate and configure the function blocks provided within the opwenPOWERLINK folder. 
The opwenPOWERLINK folder is part of 4diac's type library.

== Where to go from here?

* Go back to Protocols index: +
xref:./communication.adoc[Communication Index]
* If you want to go back to the Start Here page, we leave you here a fast access +
xref:../doc_overview.adoc[Start Here page]

Or link:#top[Go to top]
