---
# This header is for providing additional information to hugo for the website generation it ignored by asciidoctor
title: "Documentation"
page_css_file: /4diac/css/4diac_doc.css
sidebar: 
  - sb-doc
---

=  Eclipse 4diac Documentation
:lang: en
:imagesdir: intro/img


Eclipse 4diac is an open source environment for distributed industrial automation based on IEC 61499.
This documentation provides tutorials, examples, integration guides, communication references, and developer resources for Eclipse 4diac.

== Start Here

If you are new to Eclipse 4diac, these pages provide the recommended starting points.

[.landing-table]
[cols="25s,75", options="autowidth", valign="middle"]
|===
| xref:./intro/iec61499.adoc[Getting Started]
| Learn the basics of IEC 61499, Function Blocks, and distributed automation.

| xref:./intro/4diacframework.adoc[4diac Framework]
| Understand the Eclipse 4diac architecture and the interaction between 4diac IDE and 4diac FORTE.

| xref:./installation/overview.adoc[Installation]
| Install Eclipse 4diac IDE and prepare your target environment.

| xref:./tutorials/tutorials.adoc[Tutorials]
| Create, model, and deploy your first Eclipse 4diac application step by step.
|===

[.details-table]
[cols="1,1", options="invisible", width="100%", valign="top"]
|===
a|
=== Using Eclipse 4diac

Guides for application design, hardware integration, and industrial communication.

[.landing-table]
[cols="25s,75", options="autowidth"]
!===
! xref:./examples/overview.adoc[Examples]
! Explore reference applications and working systems.

! xref:./io_config/overview.adoc[IO Access]
! Connect hardware and configure peripherals for platforms such as Raspberry Pi or PLCs.

! xref:./communication/overview.adoc[Communication]
! Use industrial and IoT protocols such as MQTT, OPC UA, and Modbus.
!===

a|
=== Reference & Development

Resources for troubleshooting, advanced configuration, and platform extension.

[.landing-table]
[cols="25s,75", options="autowidth"]
!===
! xref:./faq.adoc[FAQs]
! Answers to common questions and troubleshooting scenarios.

! xref:./development/overview.adoc[Development]
! Develop custom Function Blocks, 4diac IDE plugins, and 4diac FORTE extensions.

! xref:./specs/index.adoc[Specifications]
! Review compliance profiles and project-maintained specifications.
!===
|===

---

[NOTE]
.Want to improve the documentation?
====
* Report an link:https://github.com/eclipse-4diac/4diac-documentation/issues[issue]
* Open a link:https://github.com/eclipse-4diac/4diac-documentation/pulls[pull request]
* Join the conversation on our link:https://github.com/eclipse-4diac/4diac-documentation/discussions[4diac Discussion Forum].
====
