---
title: "Replay Debugger"
url: doc/tutorials/replayDebugger.html
---

= [[topOfPage]] Replay Debugger
:lang: en
:imagesdir: img

== [[ReplayDebuggerOverview]] Overview
Replay Debugging is a powerful tool that allows you to record the execution of your application and then replay it later. This can be useful for debugging purposes, as it allows you to see exactly what happened during the execution of your application.

Tracing information is already available in the 4diac FORTE runtime. However, the current implementation traces a lot of information. Basically, it traces all events, data and also internal data from the function block.

To avoid the overhead of tracing all this information, the 4diac FORTE runtime has been extended to support a replay debugging mode. In this mode, only the output events of Service Function Blocks and their related data are traced.
In a later stage, the rest of the information is generated using a replay algorithm.

== [[CurrentStatus]] Current Status

The replay algorithm is currently implemented in the development branch of link:https://github.com/eclipse-4diac/4diac-forte/blob/develop/src/stdfblib/ita/replay[4diac FORTE].

The code is structured so that the device replayer contains one resource replayer for each resource present in the device.
The algorithm receives the output events of the Service Function Blocks and their related data. Then, the original run, corresponding to the input, can be replayed by advancing one event at a time.
Any information to be extracted from the replayed run can then be directly retrieved from the resource or device instances used to create the replayer.

=== [[Interface]] Interface
The replay debugger can be used directly programmatically by instantiating the corresponding class.

On top of the replayer, a Replay Device was added, which offers two OPC UA methods: one for loading existing traces from a given path, and another for triggering one event at a time, which returns the last execute event, or empty if it is the last event.

== [[Usage]] Usage
To enable the replay debugging capability, 4diac FORTE must be compiled with the `FORTE_TRACE_CTF` and `FORTE_TRACE_CTF_REPLAY_DEBUGGING` flags enabled.
This will enable the tracing of the output events of Service Function Blocks and their related data.

To later execute the replay algorithm, the Replay Device must be enabled, using the `FORTE_REPLAY_DEVICE` and `FORTE_TRACE_CTF_REPLAY_DEBUGGING` flags.
As OPC UA is used to communicate with the replay device, the OPC UA module must be properly enabled.

As it is now, this is the only way to use the replay debugging feature, as the concept is still under development.
Currently, an interface is being developed in 4diac IDE to allow users to easily interact with the replay device and visualize the replayed events.


== [[Testing]] Testing
The replay algorithm was tested by using different scenarios. The scenarios are tested by letting each scenario run first with the original traces (which traces all events), filtering the output events of Service Function Blocks, executing the replay algorithm, and then comparing the results of the original run with the replayed run.

The tests are located link:https://github.com/eclipse-4diac/4diac-forte/blob/develop/tests/core/trace/replayAlgorithmTest.cpp[here].

The used scenarios come from the reference examples, in the link:https://github.com/eclipse-4diac/4diac-examples/tree/master/compliance_tests[example repostory]


== Where to go from here?

You can see the supported protocols:

xref:../communication/communication.adoc[Supported Communication Protocols]

You can see the examples:

xref:../examples/examples.adoc[4diac Examples]

If you want to go back to the Where to Start page, we leave you here a fast access

xref:../doc_overview.adoc[Where to Start]

Or link:#topOfPage[Go to top]